/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CounterApp {
        /**
          * @default 0
         */
        "initial": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface CounterAppCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCounterAppElement;
}
declare global {
    interface HTMLCounterAppElementEventMap {
        "change": number;
    }
    interface HTMLCounterAppElement extends Components.CounterApp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCounterAppElementEventMap>(type: K, listener: (this: HTMLCounterAppElement, ev: CounterAppCustomEvent<HTMLCounterAppElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCounterAppElementEventMap>(type: K, listener: (this: HTMLCounterAppElement, ev: CounterAppCustomEvent<HTMLCounterAppElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCounterAppElement: {
        prototype: HTMLCounterAppElement;
        new (): HTMLCounterAppElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "counter-app": HTMLCounterAppElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CounterApp {
        /**
          * @default 0
         */
        "initial"?: number;
        "onChange"?: (event: CounterAppCustomEvent<number>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface CounterAppAttributes {
        "initial": number;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "counter-app": Omit<CounterApp, keyof CounterAppAttributes> & { [K in keyof CounterApp & keyof CounterAppAttributes]?: CounterApp[K] } & { [K in keyof CounterApp & keyof CounterAppAttributes as `attr:${K}`]?: CounterAppAttributes[K] } & { [K in keyof CounterApp & keyof CounterAppAttributes as `prop:${K}`]?: CounterApp[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "counter-app": LocalJSX.IntrinsicElements["counter-app"] & JSXBase.HTMLAttributes<HTMLCounterAppElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
